spark-yarn-master:
  command: '/etc/bootstrap-master.sh -d'
  image: jpizarrom/spark-yarn:1.6.0-master
  ports:
    - '8042:8042'
    - '8088:8088'
    - '50070:50070'
  hostname: sandbox
  container_name: sandbox
  net: my-net

spark-yarn-nodemanager:
  command: '/etc/bootstrap-nodemanager.sh -d'
  image: jpizarrom/spark-yarn:1.6.0-nodemanager
  ports:
    - '8042'
    - '8088'
    - '50070'
  hostname: slave1
  container_name: slave1
  net: my-net

spark-yarn-nodemanager2:
  command: '/etc/bootstrap-nodemanager.sh -d'
  image: jpizarrom/spark-yarn:1.6.0-nodemanager
  ports:
    - '8042'
    - '8088'
    - '50070'
  hostname: slave2
  container_name: slave2
  net: my-net

spark-yarn-nodemanager3:
  command: '/etc/bootstrap-nodemanager.sh -d'
  image: jpizarrom/spark-yarn:1.6.0-nodemanager
  hostname: slave3
  container_name: slave3
  net: my-net
